# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://thetechbytepulse.github.io/"
title: Tech Byte Pulse
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: true
buildExpired: true
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["posts", "papermod"]

minify:
  disableXML: true
  # minifyOutput: true

pagination:
  disableAliases: false
  pagerSize: 5

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 10
        - name: Categories
          url: categories/
          weight: 10
        #- name: WiKi
        #  url: https://github.com/adityatelange/hugo-PaperMod/wiki/

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Tech Byte Pulse"
  author: Prateep Gedupudi
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  # disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  # disableSpecial1stPost: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  comments: true
  giscus:
    repo: "TheTechBytePulse/thetechbytepulse.github.io"
    repoId: "R_kgDOPHqAGQ" # Get this from Giscus website
    category: "General" # Or whatever category you choose
    categoryId: "DIC_kwDOPHqAGc4CtJSX" # Get this from Giscus website
    theme: "preferred_color_scheme"
    lang: "en"
  #images: ["images/papermod-cover.png"]

  profileMode:
    enabled: false
    title: Prateep Gedupudi
    subtitle: "Exploring the pulse of technology, one byte at a time. Your guide to AI, renewable energy, and DIY tech."
    imageUrl: "images/profile.jpeg"
    imageTitle: "Prateep Gedupudi"
    imageWidth: 150
    imageHeight: 150
    buttons:
      - name: Posts
        url: /posts
      - name: Archives
        url: /archives
      - name: Tags
        url: /tags
      - name: About Me
        url: /about

  homeInfoParams:
    Title: "Tech Byte Pulse"
    Content: 
      👋 Welcome to TechBytePulse. Your ultimate destination for all things tech.
      
      - From the latest technology reviews and software tutorials to breaking tech news and in-depth industry analysis, we have got you covered. Whether you're a tech enthusiast, a professional, or just curious about the digital world.
      
      - This blog delivers bite-sized, engaging, and informative content to keep you ahead of the curve. Join us as we explore the pulse of technology, one byte at a time. 🚀💻

  socialIcons:
    - name: github
      title: View Source on Github
      url: "https://github.com/TheTechBytePulse"
    - name: youtube
      title: TechBytePulse
      url: "https://www.youtube.com/@TechBytePulse"

  
  # label:
  # iconSVG: '<svg xmlns="http://www.w3.org/2000/svg" height="25" viewBox="0 -960 960 960" fill="currentColor"><path d="M320-240h320v-80H320v80Zm0-160h320v-80H320v80ZM240-80q-33 0-56.5-23.5T160-160v-640q0-33 23.5-56.5T240-880h320l240 240v480q0 33-23.5 56.5T720-80H240Zm280-520v-200H240v640h480v-440H520ZM240-800v200-200 640-640Z"/></svg>'
  # text: "Home"
  # icon: icon.png
  # iconHeight: 35

  analytics:
       google:
           SiteVerificationTag: "G-NCMGBXTSTV"
           ID: "G-NCMGBXTSTV" # Google Analytics ID

  assets:
    disableHLJS: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/apple-touch-icon.png"

  # cover:
  #     hidden: true # hide everywhere but not in structured data
  #     hiddenInList: true # hide on list pages and home
  #     hiddenInSingle: true # hide on single page

  # fuseOpts:
  #     isCaseSensitive: false
  #     shouldSort: true
  #     location: 0
  #     distance: 1000
  #     threshold: 0.4
  #     minMatchCharLength: 0
  #     keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai

# privacy:
#   vimeo:
#     disabled: false
#     simple: true

#   twitter:
#     disabled: false
#     enableDNT: true
#     simple: true

#   instagram:
#     disabled: false
#     simple: true

#   youtube:
#     disabled: false
#     privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true