name = "DreamMod"
license = "MIT"
licenselink = "https://github.com/thetechbytepulse/thetechbytepulse.github.io/blob/main/themes/DreamMod/LICENSE"
description = "A clean, minimalist theme with a focus on content, inspired by hugo-theme-dream and PaperMod."
homepage = "https://github.com/thetechbytepulse/thetechbytepulse.github.io/"
tags = ["blog", "clean", "responsive", "minimalist", "dark-mode", "seo"]
features = ["blog", "dark-mode", "profile-mode", "search"]
min_version = "0.81.0"

[author]
  name = "Gemini"
  homepage = "https://gemini.google.com"
