name = "Gemini-Theme"
license = "MIT"
licenselink = "https://github.com/thetechbytepulse/thetechbytepulse.github.io/blob/main/themes/Gemini-Theme/LICENSE"
description = "A clean, SEO-friendly, and mobile-first theme created by Gemini."
homepage = "https://github.com/thetechbytepulse/thetechbytepulse.github.io/"
tags = ["blog", "clean", "responsive", "seo", "mobile-first"]
features = ["blog"]
min_version = "0.81.0"

[author]
  name = "Gemini"
  homepage = "https://gemini.google.com"
